### ISSUE TITLE
always use ISO-8859-1 encoding

### ISSUE THREAD

**Issue by hippasus** [povilaspanavas/RoyalMailShippingApiV2#1]
after struggling for two days, I finally find it out why this code doesn't work on side.
According to royal mail API documentation, they are using the ISO-8859-1 encoding in their system.
Which means, any hashing function on the client should use exactly the same encoding as well.

Hence, in the RoyalMailApiClient.cs file, could you kindly replace all `Encoding.Default` to `Encoding.GetEncoding("iso-8859-1")`?

Encoding.Default is OS environment related, and equals to iso-8859-1 when the OS system locale is set to English(United Kingdom). And this is why using `Encoding.Default` is discouraged...

**Comment by povilaspanavas** [comment]
Thank you for bringing it up.

Changed the encoding, ran tests on other repository, which uses Royal Mail test server and it still worked.

**Comment by Manishpce** [comment]
System.ServiceModel.FaultException: Authorisation Failure getting error when i am implementing royailmail api for print label plz help me thank you

**Comment by povilaspanavas** [comment]
Hi, @Manishpce ,

did you test it both with commit b498851742490615acecc76901aeceafde7121a1 changes and without it?

I've done it on 23 of May, just a little bit before you posted the message.

**Comment by Manishpce** [comment]
yes sir i've already changes ur correction and then implement but getting the error authorisation failure

**Comment by povilaspanavas** [comment]
In that case, are you sure your credentials are correct? Have you tried to test it manually trough Royal Mail website?

**Comment by Manishpce** [comment]
yes sir  i've tried it on royail mail website getting internal server error
