### ISSUE TITLE
HTTP request is unauthorized with client authentication scheme Anonymous, Error code 401

### ISSUE THREAD

**Issue by yxmsw2007** [povilaspanavas/RoyalMailShippingApiV2#2]
Hi, povilaspanavas, i am studying this project, and running the test case, but all failed, the error information is "HTTP request is unauthorized with client authentication scheme Anonymous", and error code is 401, i had modified appSettings label of App.config with me, i don't know what wrong is happend, do you have any recommends?
by the way, what is "RoyalMailApiApplicationId"? i can only get the application name, no id, how can i get it
thks

**Comment by dskhati01** [comment]
Hi
You would need test credentials and these details from Royal Mail.

Thanks

**Comment by povilaspanavas** [comment]
RoyalMail Api is quite bad with error descriptions. It says that the project is trying to authenticate with the anonymous scheme, but that, of course, is not true. Something probably is wrong with the credentials.

dskhati01 is correct. You need to get credentials from Royal Mail.

Royal Mail in email provides:
Username
Password
Application Id (all my application ids are the same, even when we are shipping using customer accounts)

Meanwhile, the clientId and secret can be retrieved from https://developer.royalmail.net

I hope that helps.

**Comment by yxmsw2007** [comment]
Thx dskhati01 and povilaspanavas, I have resolved the problem, because i devolep on a third platform, and some problem can not resolve, so i want to use this project to check my message, Now, the problem has been resolved, thx for your help.
